"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commodities',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_name'), 'commodities', ['name'], unique=False)
    op.create_table('number_sequences',
    sa.Column('prefix', sa.String(length=60), nullable=False),
    sa.Column('last', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('otp_challenges',
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'register', 'verify_mobile', 'verify_email', 'delete_account', 'reset_password', name='otppurpose', native_enum=False, length=30), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_target'), 'otp_challenges', ['target'], unique=False)
    op.create_table('states',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('commodity_links',
    sa.Column('owner_type', sa.Enum('user', 'seller', 'buyer', 'lot', 'supply', 'demand', 'provider', 'catalog', 'license', 'booking', 'agreement', 'bill', name='ownertype', native_enum=False, length=30), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('preferred', 'expertise', 'handled', name='commodityrole', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'commodity_id', 'role', name='uq_commodity_link')
    )
    op.create_index(op.f('ix_commodity_links_commodity_id'), 'commodity_links', ['commodity_id'], unique=False)
    op.create_table('commodity_varieties',
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodity_varieties_commodity_id'), 'commodity_varieties', ['commodity_id'], unique=False)
    op.create_table('districts',
    sa.Column('state_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('apmcs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('apmc_type', sa.Enum('enam', 'non_enam', name='apmctype', native_enum=False, length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apmcs_district_id'), 'apmcs', ['district_id'], unique=False)
    op.create_index(op.f('ix_apmcs_name'), 'apmcs', ['name'], unique=False)
    op.create_index(op.f('ix_apmcs_state_id'), 'apmcs', ['state_id'], unique=False)
    op.create_table('tehsils',
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tehsils_district_id'), 'tehsils', ['district_id'], unique=False)
    op.create_table('addresses',
    sa.Column('owner_type', sa.Enum('user', 'seller', 'buyer', 'lot', 'supply', 'demand', 'provider', 'catalog', 'license', 'booking', 'agreement', 'bill', name='ownertype', native_enum=False, length=30), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('permanent', 'current', 'service_area', 'preferred', 'lot', 'delivery', 'pickup', 'drop', name='addresskind', native_enum=False, length=30), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=True),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('tehsil_id', sa.BigInteger(), nullable=True),
    sa.Column('apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['tehsil_id'], ['tehsils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_apmc_id'), 'addresses', ['apmc_id'], unique=False)
    op.create_index('ix_addresses_owner', 'addresses', ['owner_type', 'owner_id', 'kind'], unique=False)
    op.create_index(op.f('ix_addresses_state_id'), 'addresses', ['state_id'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.String(length=36), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('registered_apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_relation', sa.String(length=10), nullable=True),
    sa.Column('guardian_name', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', native_enum=False, length=30), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alt_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registered_apmc_id'], ['apmcs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('attachments',
    sa.Column('owner_type', sa.Enum('user', 'seller', 'buyer', 'lot', 'supply', 'demand', 'provider', 'catalog', 'license', 'booking', 'agreement', 'bill', name='ownertype', native_enum=False, length=30), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_owner', 'attachments', ['owner_type', 'owner_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc', sa.String(length=20), nullable=False),
    sa.Column('holder_name', sa.String(length=200), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_index('uq_one_primary_bank', 'bank_accounts', ['user_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('buyers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_buyers_organization'), 'buyers', ['organization'], unique=False)
    op.create_table('commission_agents',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('apmc_id', sa.BigInteger(), nullable=False),
    sa.Column('firm_name', sa.String(length=200), nullable=False),
    sa.Column('agent_name', sa.String(length=150), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_agents_apmc_id'), 'commission_agents', ['apmc_id'], unique=False)
    op.create_index(op.f('ix_commission_agents_firm_name'), 'commission_agents', ['firm_name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sellers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_type', sa.Enum('farmer', 'fpo', name='sellertype', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('service_providers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('notify_by_phone', sa.Boolean(), nullable=False),
    sa.Column('notify_by_email', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('demands',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('is_advance', sa.Boolean(), nullable=False),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('variety_id', sa.BigInteger(), nullable=True),
    sa.Column('min_qty_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_qty_qtl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deliver_by', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['commodity_varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_demands_buyer_id'), 'demands', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_demands_commodity_id'), 'demands', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_demands_status'), 'demands', ['status'], unique=False)
    op.create_table('epermits',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('source_state_id', sa.BigInteger(), nullable=True),
    sa.Column('source_apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('commodity_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity_qtl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['source_apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['source_state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('provider_services',
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('service_type', sa.Enum('weighment', 'warehouse', 'logistics', 'assaying', 'assurance', 'packaging', 'grading', 'labour', name='servicetype', native_enum=False, length=30), nullable=False),
    sa.Column('shop_name', sa.String(length=200), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expires_on', sa.Date(), nullable=True),
    sa.Column('response_time', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'service_type', name='uq_provider_service_type')
    )
    op.create_index(op.f('ix_provider_services_provider_id'), 'provider_services', ['provider_id'], unique=False)
    op.create_table('supplies',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('variety_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expected_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('available_to', sa.Date(), nullable=False),
    sa.Column('delivery_mode', sa.Enum('delivery', 'pickup', name='deliverymode', native_enum=False, length=30), nullable=False),
    sa.Column('contact_by_phone', sa.Boolean(), nullable=False),
    sa.Column('contact_by_email', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variety_id'], ['commodity_varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_supplies_commodity_id'), 'supplies', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_supplies_seller_id'), 'supplies', ['seller_id'], unique=False)
    op.create_table('trade_licenses',
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('issuing_state_id', sa.BigInteger(), nullable=True),
    sa.Column('issuing_apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('operating_state_id', sa.BigInteger(), nullable=True),
    sa.Column('operating_apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('is_unified', sa.Boolean(), nullable=False),
    sa.Column('apmc_type', sa.Enum('enam', 'non_enam', name='apmctype', native_enum=False, length=30), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'suspended', name='licensestatus', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issuing_apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['issuing_state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['operating_apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['operating_state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'number', name='uq_buyer_license_number')
    )
    op.create_index(op.f('ix_trade_licenses_buyer_id'), 'trade_licenses', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_trade_licenses_operating_apmc_id'), 'trade_licenses', ['operating_apmc_id'], unique=False)
    op.create_index(op.f('ix_trade_licenses_operating_state_id'), 'trade_licenses', ['operating_state_id'], unique=False)
    op.create_table('equipment',
    sa.Column('provider_service_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('capacity_tonnes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('calibration_cert_no', sa.String(length=100), nullable=True),
    sa.Column('calibration_expires_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_service_id'], ['provider_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_calibration_expires_on'), 'equipment', ['calibration_expires_on'], unique=False)
    op.create_index(op.f('ix_equipment_provider_service_id'), 'equipment', ['provider_service_id'], unique=False)
    op.create_table('lots',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_type', sa.Enum('advance', 'outside_apmc', name='lottype', native_enum=False, length=30), nullable=False),
    sa.Column('sale_type', sa.Enum('primary', 'secondary', name='saletype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'auctioned', 'sold', 'cancelled', 'expired', name='lotstatus', native_enum=False, length=30), nullable=False),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('variety_id', sa.BigInteger(), nullable=True),
    sa.Column('speciality', sa.String(length=255), nullable=True),
    sa.Column('bag_type_id', sa.BigInteger(), nullable=True),
    sa.Column('bags', sa.Integer(), nullable=True),
    sa.Column('quantity_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('commission_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('delivery_mode', sa.Enum('delivery', 'pickup', name='deliverymode', native_enum=False, length=30), nullable=True),
    sa.Column('epermit_id', sa.BigInteger(), nullable=True),
    sa.Column('source_state_id', sa.BigInteger(), nullable=True),
    sa.Column('source_apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('is_enam_trade', sa.Boolean(), nullable=True),
    sa.Column('fee_applicable', sa.Boolean(), nullable=False),
    sa.Column('bid_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_duration_min', sa.Integer(), nullable=True),
    sa.Column('result_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_closed_bid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['bag_type_id'], ['bag_types.id'], ),
    sa.ForeignKeyConstraint(['commission_agent_id'], ['commission_agents.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['epermit_id'], ['epermits.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['source_state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['commodity_varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_lots_apmc_id'), 'lots', ['apmc_id'], unique=False)
    op.create_index(op.f('ix_lots_commodity_id'), 'lots', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_lots_seller_id'), 'lots', ['seller_id'], unique=False)
    op.create_index('ix_lots_seller_status', 'lots', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_table('service_catalogs',
    sa.Column('provider_service_id', sa.BigInteger(), nullable=False),
    sa.Column('service_type', sa.Enum('weighment', 'warehouse', 'logistics', 'assaying', 'assurance', 'packaging', 'grading', 'labour', name='servicetype', native_enum=False, length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.Enum('inside_apmc', 'outside_apmc', name='venue', native_enum=False, length=30), nullable=False),
    sa.Column('apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('commodity_id', sa.BigInteger(), nullable=True),
    sa.Column('variety_id', sa.BigInteger(), nullable=True),
    sa.Column('price_unit', sa.String(length=30), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), nullable=False),
    sa.Column('turnaround', sa.String(length=100), nullable=True),
    sa.Column('operating_hours', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['provider_service_id'], ['provider_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['commodity_varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_search', 'service_catalogs', ['service_type', 'venue', 'state_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_service_catalogs_apmc_id'), 'service_catalogs', ['apmc_id'], unique=False)
    op.create_index(op.f('ix_service_catalogs_commodity_id'), 'service_catalogs', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_service_catalogs_name'), 'service_catalogs', ['name'], unique=False)
    op.create_index(op.f('ix_service_catalogs_provider_service_id'), 'service_catalogs', ['provider_service_id'], unique=False)
    op.create_index(op.f('ix_service_catalogs_service_type'), 'service_catalogs', ['service_type'], unique=False)
    op.create_index(op.f('ix_service_catalogs_state_id'), 'service_catalogs', ['state_id'], unique=False)
    op.create_index(op.f('ix_service_catalogs_venue'), 'service_catalogs', ['venue'], unique=False)
    op.create_table('auctions',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'closed', 'declared', 'rejected', 'cancelled', name='auctionstatus', native_enum=False, length=30), nullable=False),
    sa.Column('is_closed_bid', sa.Boolean(), nullable=False),
    sa.Column('is_auto_declare', sa.Boolean(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reserve_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('min_increment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('h1_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('h1_bid_id', sa.BigInteger(), nullable=True),
    sa.Column('bid_count', sa.Integer(), nullable=False),
    sa.Column('bidder_count', sa.Integer(), nullable=False),
    sa.Column('winning_buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('winning_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_buyer_id'], ['buyers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_auctions_status_end', 'auctions', ['status', 'ends_at'], unique=False)
    op.create_table('service_bookings',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('service_type', sa.Enum('weighment', 'warehouse', 'logistics', 'assaying', 'assurance', 'packaging', 'grading', 'labour', name='servicetype', native_enum=False, length=30), nullable=False),
    sa.Column('seeker_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('venue', sa.Enum('inside_apmc', 'outside_apmc', name='venue', native_enum=False, length=30), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('scheduled_on', sa.Date(), nullable=True),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('quantity_qtl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('quoted_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('offered_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('counter_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('negotiation', sa.Enum('na', 'requested', 'countered', 'accepted', 'rejected', name='negotiationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('requested', 'negotiating', 'accepted', 'in_progress', 'completed', 'cancelled', 'rejected', name='bookingstatus', native_enum=False, length=30), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'overdue', 'failed', name='paymentstatus', native_enum=False, length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['service_catalogs.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_booking_provider_status', 'service_bookings', ['provider_id', 'status'], unique=False)
    op.create_index(op.f('ix_service_bookings_catalog_id'), 'service_bookings', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_service_bookings_provider_id'), 'service_bookings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_bookings_seeker_id'), 'service_bookings', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_service_bookings_service_type'), 'service_bookings', ['service_type'], unique=False)
    op.create_index(op.f('ix_service_bookings_status'), 'service_bookings', ['status'], unique=False)
    op.create_table('auction_bids',
    sa.Column('auction_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'outbid', 'winning', 'rejected', name='bidstatus', native_enum=False, length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_auction_bids_auction_id'), 'auction_bids', ['auction_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_buyer_id'), 'auction_bids', ['buyer_id'], unique=False)
    op.create_index('ix_bids_auction_price', 'auction_bids', ['auction_id', 'price'], unique=False)
    op.create_table('weighment_records',
    sa.Column('slip_number', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('bag_type_id', sa.BigInteger(), nullable=True),
    sa.Column('number_of_bags', sa.Integer(), nullable=True),
    sa.Column('gross_kg', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tare_kg', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bag_deduction_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('equipment_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bag_type_id'], ['bag_types.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['service_bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_number')
    )
    op.create_index(op.f('ix_weighment_records_lot_id'), 'weighment_records', ['lot_id'], unique=False)
    op.create_index(op.f('ix_weighment_records_vehicle_number'), 'weighment_records', ['vehicle_number'], unique=False)
    op.create_table('trades',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('agreement_number', sa.String(length=50), nullable=True),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('auction_id', sa.BigInteger(), nullable=True),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('commission_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('apmc_id', sa.BigInteger(), nullable=True),
    sa.Column('venue', sa.Enum('inside_apmc', 'outside_apmc', name='venue', native_enum=False, length=30), nullable=False),
    sa.Column('bags', sa.Integer(), nullable=True),
    sa.Column('approx_qty_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rate_per_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('weighment_id', sa.BigInteger(), nullable=True),
    sa.Column('final_qty_qtl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('declared', 'confirmed', 'weighment_pending', 'agreement_generated', 'cancelled', name='tradestatus', native_enum=False, length=30), nullable=False),
    sa.Column('buyer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_approval', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False, length=30), nullable=False),
    sa.Column('seller_approval', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False, length=30), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apmc_id'], ['apmcs.id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['commission_agent_id'], ['commission_agents.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['weighment_id'], ['weighment_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_number'),
    sa.UniqueConstraint('lot_id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_trades_apmc_id'), 'trades', ['apmc_id'], unique=False)
    op.create_index(op.f('ix_trades_buyer_id'), 'trades', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_trades_seller_id'), 'trades', ['seller_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_venue'), 'trades', ['venue'], unique=False)
    op.create_table('sale_bills',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('quantity_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rate_per_qtl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('mandi_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('other_charges', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'overdue', 'failed', name='paymentstatus', native_enum=False, length=30), nullable=False),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index(op.f('ix_sale_bills_payment_status'), 'sale_bills', ['payment_status'], unique=False)
    op.create_table('gate_exits',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('exit_type', sa.Enum('post_trade', 'goods_return', name='gateexittype', native_enum=False, length=30), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('bill_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('bags', sa.Integer(), nullable=True),
    sa.Column('quantity_qtl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('approval', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False, length=30), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bill_id'], ['sale_bills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_gate_exits_approval'), 'gate_exits', ['approval'], unique=False)
    op.create_index(op.f('ix_gate_exits_exit_type'), 'gate_exits', ['exit_type'], unique=False)
    op.create_index(op.f('ix_gate_exits_lot_id'), 'gate_exits', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_exits_lot_id'), table_name='gate_exits')
    op.drop_index(op.f('ix_gate_exits_exit_type'), table_name='gate_exits')
    op.drop_index(op.f('ix_gate_exits_approval'), table_name='gate_exits')
    op.drop_table('gate_exits')
    op.drop_index(op.f('ix_sale_bills_payment_status'), table_name='sale_bills')
    op.drop_table('sale_bills')
    op.drop_index(op.f('ix_trades_venue'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_seller_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_buyer_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_apmc_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_weighment_records_vehicle_number'), table_name='weighment_records')
    op.drop_index(op.f('ix_weighment_records_lot_id'), table_name='weighment_records')
    op.drop_table('weighment_records')
    op.drop_index('ix_bids_auction_price', table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_buyer_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_auction_id'), table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_index(op.f('ix_service_bookings_status'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_service_type'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_seeker_id'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_provider_id'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_catalog_id'), table_name='service_bookings')
    op.drop_index('ix_booking_provider_status', table_name='service_bookings')
    op.drop_table('service_bookings')
    op.drop_index('ix_auctions_status_end', table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_service_catalogs_venue'), table_name='service_catalogs')
    op.drop_index(op.f('ix_service_catalogs_state_id'), table_name='service_catalogs')
    op.drop_index(op.f('ix_service_catalogs_service_type'), table_name='service_catalogs')
    op.drop_index(op.f('ix_service_catalogs_provider_service_id'), table_name='service_catalogs')
    op.drop_index(op.f('ix_service_catalogs_name'), table_name='service_catalogs')
    op.drop_index(op.f('ix_service_catalogs_commodity_id'), table_name='service_catalogs')
    op.drop_index(op.f('ix_service_catalogs_apmc_id'), table_name='service_catalogs')
    op.drop_index('ix_catalog_search', table_name='service_catalogs')
    op.drop_table('service_catalogs')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index('ix_lots_seller_status', table_name='lots')
    op.drop_index(op.f('ix_lots_seller_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_commodity_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_apmc_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_equipment_provider_service_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_calibration_expires_on'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_trade_licenses_operating_state_id'), table_name='trade_licenses')
    op.drop_index(op.f('ix_trade_licenses_operating_apmc_id'), table_name='trade_licenses')
    op.drop_index(op.f('ix_trade_licenses_buyer_id'), table_name='trade_licenses')
    op.drop_table('trade_licenses')
    op.drop_index(op.f('ix_supplies_seller_id'), table_name='supplies')
    op.drop_index(op.f('ix_supplies_commodity_id'), table_name='supplies')
    op.drop_table('supplies')
    op.drop_index(op.f('ix_provider_services_provider_id'), table_name='provider_services')
    op.drop_table('provider_services')
    op.drop_table('epermits')
    op.drop_index(op.f('ix_demands_status'), table_name='demands')
    op.drop_index(op.f('ix_demands_commodity_id'), table_name='demands')
    op.drop_index(op.f('ix_demands_buyer_id'), table_name='demands')
    op.drop_table('demands')
    op.drop_table('service_providers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_commission_agents_firm_name'), table_name='commission_agents')
    op.drop_index(op.f('ix_commission_agents_apmc_id'), table_name='commission_agents')
    op.drop_table('commission_agents')
    op.drop_index(op.f('ix_buyers_organization'), table_name='buyers')
    op.drop_table('buyers')
    op.drop_index('uq_one_primary_bank', table_name='bank_accounts', postgresql_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index('ix_attachments_owner', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('users')
    op.drop_index(op.f('ix_addresses_state_id'), table_name='addresses')
    op.drop_index('ix_addresses_owner', table_name='addresses')
    op.drop_index(op.f('ix_addresses_apmc_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_tehsils_district_id'), table_name='tehsils')
    op.drop_table('tehsils')
    op.drop_index(op.f('ix_apmcs_state_id'), table_name='apmcs')
    op.drop_index(op.f('ix_apmcs_name'), table_name='apmcs')
    op.drop_index(op.f('ix_apmcs_district_id'), table_name='apmcs')
    op.drop_table('apmcs')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_commodity_varieties_commodity_id'), table_name='commodity_varieties')
    op.drop_table('commodity_varieties')
    op.drop_index(op.f('ix_commodity_links_commodity_id'), table_name='commodity_links')
    op.drop_table('commodity_links')
    op.drop_table('states')
    op.drop_index(op.f('ix_otp_challenges_target'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_table('number_sequences')
    op.drop_index(op.f('ix_commodities_name'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_table('bag_types')
    # ### end Alembic commands ###
